# Cloud Buildpacks deployment.
# IMPORTANT: Set trigger source to the app folder (default: cloud-run-service).
# This avoids: "No buildpack groups passed detection".
substitutions:
  _APP_DIR: cloud-run-service
  _REGION: us-central1
  _SERVICE: discover-egypt-service

steps:
  - name: gcr.io/k8s-skaffold/pack
    id: Build image with buildpacks
    dir: ${_APP_DIR}
    entrypoint: pack
    args:
      - build
      - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/${_SERVICE}:${SHORT_SHA}
      - --builder
      - gcr.io/buildpacks/builder

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: Push and deploy to Cloud Run
    entrypoint: bash
    args:
      - -c
      - |
        gcloud auth configure-docker ${_REGION}-docker.pkg.dev --quiet
        docker push ${_REGION}-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/${_SERVICE}:${SHORT_SHA}
        gcloud run deploy ${_SERVICE} \
          --image ${_REGION}-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/${_SERVICE}:${SHORT_SHA} \
          --region ${_REGION} \
          --platform managed \
          --allow-unauthenticated

images:
  - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/${_SERVICE}:${SHORT_SHA}
